version: "3.4"

x-common-variables: &common-variables
  MYSQL_DATABASE: SMsonglist
  MYSQL_USER: sw_user
  MYSQL_PASSWORD: 'Y71o8QcQNn'
  SECRET_KEY: 'benis'

services:
  php:
    build: './docker/php/'
    environment:
      <<: *common-variables
    networks:
      - backend
    volumes:
      - ./request_list/:/var/www/html/
  apache:
    build: './docker/apache/'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./request_list/:/var/www/html/
  mysql:
    image: mysql:5.6.40
    environment:
      <<: *common-variables
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    ports:
      - '3306:3306'
    networks:
      - backend
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
  chatbot:
    build: './chatbot/'
    environment:
      <<: *common-variables
      BOTUSERNAME: 'your-bot'
      BOTPASSWORD: 'oauth:your-key'
      BOTCHANNEL: 'your-channel'
      URLBASE: 'http://apache'
    networks:
      - backend
networks:
  frontend:
  backend: