version: "3.4"

x-common-variables: &common-variables
  MYSQL_DATABASE: sm_software
  MYSQL_USER: sw_user
  MYSQL_PASSWORD: Y71o8QcQNn

services:
  php:
    build: './docker/php/'
    environment:
      <<: *common-variables
      SECRET_KEY: 'benis'
    networks:
      - backend
    volumes:
      - ./request_list/:/var/www/html/
  apache:
    build: './docker/apache/'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./request_list/:/var/www/html/
  mysql:
    image: mysql:5.6.40
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: 'cIBwDcRgso'
    networks:
      - backend
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
networks:
  frontend:
  backend: